services:
  db:
    image: postgres:17
    container_name: asset_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: asset_management

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d asset_management"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .

    container_name: asset_api

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env

    ports:
      - "8000:8000"

volumes:
  postgres_data:
