services:
    db:
        image: postgres:17

        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: asset_management

        ports:
            - "5432:5432"

        volumes:
            - postgres_data:/var/lib/postgresql/data

        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d asset_management"]
            interval: 5s
            timeout: 5s
            retries: 5

    worker:
        build: .
        command: celery -A celery_app worker --loglevel=info # Override command in dockerFile
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        env_file:
            - .env

    api:
        build: .

        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy

        env_file:
            - .env

        ports:
            - "8000:8000"

    redis:
        image: redis:7-alpine

        command: ["redis-server", "--appendonly", "yes"]

        ports:
            - "6379:6379"

        volumes:
            - redis_data:/data

        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
    redis_data:
