"""initial tables structure

Revision ID: 749eb58ed1c2
Revises: 
Create Date: 2026-06-23 15:04:10.017413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '749eb58ed1c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DOMAIN', 'SUBDOMAIN', 'IP_ADDRESS', 'SERVICE', 'CERTIFICATE', 'TECHNOLOGY', name='assettype'), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STALE', 'ARCHIVED', name='assetstatus'), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('PARENT', 'COVERS', 'DETECTED_ON', 'RESOLVES_TO', 'RUNS_ON', name='relationtype'), nullable=False),
    sa.ForeignKeyConstraint(['from_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('from_id', 'to_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relations')
    op.drop_table('assets')
    op.drop_table('organizations')
    # ### end Alembic commands ###
