"""Added asset source enum

Revision ID: e44c87f4db91
Revises: a1b2c3d4e5f6
Create Date: 2026-06-24 17:31:11.709615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e44c87f4db91'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    assetsource = sa.Enum(
        "IMPORT",
        "SCAN",
        "MANUAL",
        name="assetsource",
    )

    assetsource.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        "assets",
        "source",
        existing_type=postgresql.ARRAY(sa.VARCHAR()),
        type_=postgresql.ARRAY(assetsource),
        existing_nullable=False,
        postgresql_using="source::assetsource[]",
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'source',
               existing_type=postgresql.ARRAY(sa.Enum('Import', 'SCAN', 'Manual', name='assetsource')),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=False)
    # ### end Alembic commands ###
