"""Added unique asset constraint

Revision ID: e6d7ed38c059
Revises: 749eb58ed1c2
Create Date: 2026-06-24 12:23:09.760633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d7ed38c059'
down_revision: Union[str, Sequence[str], None] = '749eb58ed1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assets', ['type', 'value', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assets', type_='unique')
    # ### end Alembic commands ###
